[versions]
spigot = "1.16.5-R0.1-SNAPSHOT"

placeholder = "2.11.1"

[libraries]
spigot = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "spigot" }

placeholder = { group = "me.clip", name = "placeholderapi", version.ref = "placeholder" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2"}